### ISSUE TITLE
App gets stuck while creating the IndexRequest

### ISSUE THREAD

**Issue by ivangfr** [micronaut-projects/micronaut-elasticsearch#188]
Hi, I've just updated my [micronaut-elasticsearch](https://github.com/ivangfr/graalvm-quarkus-micronaut-springboot/tree/master/elasticsearch/micronaut-elasticsearch) to **Micronaut** `2.5.2`.

I can build the native image and start its container without any problem. However, when I try to save a `movie`, the app gets stuck. I've added some debug logging in order to try to find the problem.

Here is my output
```
 __  __ _                                  _
|  \/  (_) ___ _ __ ___  _ __   __ _ _   _| |_
| |\/| | |/ __| '__/ _ \| '_ \ / _` | | | | __|
| |  | | | (__| | | (_) | | | | (_| | |_| | |_
|_|  |_|_|\___|_|  \___/|_| |_|\__,_|\__,_|\__|
  Micronaut (v2.5.2)

13:29:27.982 [main] INFO  i.m.context.env.DefaultEnvironment - Established active environments: [native]
13:29:28.005 [ForkJoinPool.commonPool-worker-5] WARN  i.m.c.i.binder.jvm.JvmGcMetrics - GC notifications will not be available because MemoryPoolMXBeans are not provided by the JVM
13:29:28.008 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 141322ms. Server Running: http://05d134f6d06e:8080
13:29:32.294 [default-nioEventLoopGroup-1-2] INFO  c.m.m.service.MovieServiceImpl - 1 - Movie(imdb=789, title=Resident Evil)
13:29:32.294 [default-nioEventLoopGroup-1-2] INFO  c.m.m.service.MovieServiceImpl - 2 - {"imdb":"789","title":"Resident Evil"}
```

> **Note:** the startup time is `14s`

Looks like it's getting stuck while creating the IndexRequest
```
IndexRequest indexRequest = new IndexRequest(moviesIndex).source(movieAsJsonString, XContentType.JSON);
```

### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

- git clone https://github.com/ivangfr/graalvm-quarkus-micronaut-springboot.git
- cd graalvm-quarkus-micronaut-springboot
- git micronaut-elasticsearch-issue-188
- cd elasticsearch
- docker-compose up -d
- cd micronaut-elasticsearch
- ./mvnw clean
- ./docker-build.sh native
- docker run --rm --name micronaut-elasticsearch-native -p 9115:8080 -e MICRONAUT_ENVIRONMENTS=native -e ELASTICSEARCH_HOST=elasticsearch --network elasticsearch_default docker.mycompany.com/micronaut-elasticsearch-native:1.0.0
- curl -i -X POST "localhost:9115/api/movies" -H "Content-type: application/json" -d '{"imdb": "789", "title": "Resident Evil"}'

### Expected Behaviour

Record indexed in `Elasticsearch`

### Actual Behaviour

App is getting stuck while creating the `IndexRequest`

### Environment Information

- **Operating System**: MacOS
- **Micronaut Version:** 2.5.2
- **JDK Version:** 11

### Example Application

- https://github.com/ivangfr/graalvm-quarkus-micronaut-springboot/tree/master/elasticsearch/micronaut-elasticsearch

**Comment by ilopmar** [comment]
I've tried with Micronaut 3 and it works properly.
