### ISSUE TITLE
Missing links in "Health" section in documentation

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-elasticsearch#2]
There are a few missing links here:
![image](https://user-images.githubusercontent.com/559192/48913497-d31a4300-ee78-11e8-9952-9b5e9bfbcaef.png)

**Comment by puneetbehl** [comment]
It seems to be fixed in the [snapshot version](https://micronaut-projects.github.io/micronaut-elasticsearch/snapshot/guide/index.html#healthChecks) so it should be there with next release.
