### ISSUE TITLE
Minor documentation issue - wrong link

### ISSUE THREAD

**Issue by javapapo** [micronaut-projects/micronaut-elasticsearch#24]
Apologies I am not - super familiar with asciidoc  - On the following link

https://micronaut-projects.github.io/micronaut-elasticsearch/latest/guide/index.html

And specifically on this line

`See the API for DefaultElasticsearchConfigurationProperties for more information on the available configuration options.`

The documentation links to `https://micronaut-projects.github.io/micronaut-elasticsearch/latest/api/io/micronaut/configuration/mongo/reactive/DefaultElasticsearchConfigurationProperties.html` which seems to be wrong

the relevant asciidoc section is 

```text
See the API for api:configuration.elasticsearch.DefaultElasticsearchConfigurationProperties[] for more information on the available configuration options.
```

I think it should point here -> `https://micronaut-projects.github.io/micronaut-elasticsearch/latest/api/io/micronaut/configuration/elasticsearch/DefaultElasticsearchConfigurationProperties.html`

**Comment by ilopmar** [comment]
It's already fixed in the snapshot docs: https://micronaut-projects.github.io/micronaut-elasticsearch/snapshot/guide/index.html
