### ISSUE TITLE
Could not initialize class org.elasticsearch.client.RestClient

### ISSUE THREAD

**Issue by ivangfr** [micronaut-projects/micronaut-elasticsearch#34]
Hi,

I've implemented a **Micronaut** (`2.0.0.M3`) with **Elasticsearch** (`7.6.2`). Here is my project [`graalvm-quarkus-micronaut-springboot/elasticsearch/micronaut-elasticsearch`](https://github.com/ivangfr/graalvm-quarkus-micronaut-springboot/tree/master/elasticsearch/micronaut-elasticsearch)

I didn't have any problem running it in development mode (`./gradlew clean run`) or as a Docker container (non-native); except, I had problem running it in native mode.

Basically, I am able to build the Native Docker Image and spin a Docker container of it. However, when I make a request to the Rest API, I get an exception

```
Message: Could not initialize class org.elasticsearch.client.RestClient
Path Taken: new $MovieControllerDefinition$Intercepted([MovieService movieService],MovieMapper   movieMapper,BeanContext beanContext,Qualifier qualifier,Interceptor[] interceptors) --> new   MovieServiceImpl([RestHighLevelClient client],MovieMapper movieMapper,ObjectMapper objectMapper)
io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [com.  mycompany.service.MovieServiceImpl]

Message: Could not initialize class org.elasticsearch.client.RestClient
Path Taken: new $MovieControllerDefinition$Intercepted([MovieService movieService],MovieMapper   movieMapper,BeanContext beanContext,Qualifier qualifier,Interceptor[] interceptors) --> new   MovieServiceImpl([RestHighLevelClient client],MovieMapper movieMapper,ObjectMapper objectMapper)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1840)
	at io.micronaut.context.DefaultBeanContext.getScopedBeanForDefinition(DefaultBeanContext.java:2309)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2224)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2196)
...
```
> For complete stack trace see [here](https://github.com/ivangfr/graalvm-quarkus-micronaut-springboot/tree/master/elasticsearch/micronaut-elasticsearch#issues)

It seems that the `class org.elasticsearch.client.RestClient` bean is not been initialized. I am using `micronaut-elasticsearch` dependency as you can see in the [`build.gradle`](https://github.com/ivangfr/graalvm-quarkus-micronaut-springboot/blob/master/elasticsearch/micronaut-elasticsearch/build.gradle).

Thanks

**Comment by graemerocher** [comment]
Looks like we still have some work to get elastic search working on GraalVM native

**Comment by ilopmar** [comment]
@ivangfr I've adapted your test application, you can find my version here: https://github.com/micronaut-graal-tests/micronaut-elasticsearch-graal.
I don't have experience with Elasticsearch so if you want to try different usages or contribute to new things, a PR will be welcome :)

Please also keep in mind that you don't need to define a factory to create an `ObjectMapper` bean, Micronaut already does that so you can inject it where you need it. You can remove this class: https://github.com/ivangfr/graalvm-quarkus-micronaut-springboot/blob/master/elasticsearch/micronaut-elasticsearch/src/main/java/com/mycompany/config/ObjectMapperFactory.java

**Comment by ivangfr** [comment]
Great @ilopmar Sure, whenever I have time I can contribute.
Thanks for the `ObjectMapper` tip btw!
