### ISSUE TITLE
Missing link to DefaultElasticsearchConfigurationProperties

### ISSUE THREAD

**Issue by ysb33r** [micronaut-projects/micronaut-elasticsearch#8]
The link to https://micronaut-projects.github.io/micronaut-elasticsearch/latest/api/io/micronaut/configuration/mongo/reactive/DefaultElasticsearchConfigurationProperties.html

![image](https://user-images.githubusercontent.com/907624/69035501-1e135b80-09e4-11ea-8c4c-a1944a5152c4.png)

yields a 404.

**Comment by ilopmar** [comment]
Fixed to link to the correct documentation. Already available in the snapshot docs: https://micronaut-projects.github.io/micronaut-elasticsearch/snapshot/guide/index.html
